//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sehirTanitimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bolgeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bolgeler()
        {
            this.Illers = new HashSet<Iller>();
        }
    
        public int bolge_id { get; set; }
        public string ad { get; set; }
        public Nullable<int> sehirSayisi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Iller> Illers { get; set; }
    }
}
