//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sehirTanitimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Iller()
        {
            this.Nufus = new HashSet<Nufu>();
        }
    
        public int plaka { get; set; }
        public string sehir_adi { get; set; }
        public Nullable<int> rakim { get; set; }
        public Nullable<int> bolge_id { get; set; }
        public Nullable<int> nufus_id { get; set; }
        public Nullable<int> tel_kodu { get; set; }
    
        public virtual Bolgeler Bolgeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nufu> Nufus { get; set; }
    }
}
