//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sehirTanitimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nufu
    {
        public int Id { get; set; }
        public Nullable<int> toplamNufus { get; set; }
        public Nullable<int> iller_plaka { get; set; }
    
        public virtual Iller Iller { get; set; }
    }
}
